### ISSUE TITLE
JSON error getting ansible.windows collection versions

### ISSUE THREAD

**Issue by jcox10** [briantist/galactory#58]
I'm getting a JSON parse error when galaxy tries to get the `ansible.windows` collection. I can't figure out the source JSON to see the character number its complaining about. This is the only collection that has an issue, all the other collections download just fine. (We don't use ansible on windows, but one of the roles requires the collection).

```
ERROR:galactory:Exception on /api/v2/collections/ansible/windows/versions/ [GET]
galactory_1  | Traceback (most recent call last):
galactory_1  |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
galactory_1  |     response = self.full_dispatch_request()
galactory_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
galactory_1  |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
galactory_1  |     rv = self.handle_user_exception(e)
galactory_1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
galactory_1  |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
galactory_1  |     rv = self.dispatch_request()
galactory_1  |          ^^^^^^^^^^^^^^^^^^^^^^^
galactory_1  |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
galactory_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
galactory_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
galactory_1  |   File "/venv/lib/python3.11/site-packages/galactory/api/v2/collections.py", line 84, in versions
galactory_1  |     collections = collected_collections(repository, namespace=namespace, name=collection, scheme=scheme)
galactory_1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
galactory_1  |   File "/venv/lib/python3.11/site-packages/galactory/utilities.py", line 143, in collected_collections
galactory_1  |     for c in discover_collections(repo, namespace=namespace, name=name, scheme=scheme):
galactory_1  |   File "/venv/lib/python3.11/site-packages/galactory/utilities.py", line 107, in discover_collections
galactory_1  |     collection_info = json.loads(props['collection_info'][0])
galactory_1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
galactory_1  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
galactory_1  |     return _default_decoder.decode(s)
galactory_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
galactory_1  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
galactory_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
galactory_1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
galactory_1  |   File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
galactory_1  |     obj, end = self.scan_once(s, idx)
galactory_1  |                ^^^^^^^^^^^^^^^^^^^^^^
galactory_1  | json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 543 (char 542)
galactory_1  | 172.18.0.1 - - [09/Mar/2023:21:59:17 +0000] "GET /api/v2/collections/ansible/windows/versions/?page_size=100 HTTP/1.0" 500 265 "-" "ansible-galaxy/2.13.3 (Linux; python:3.8.10)"
```

**Comment by briantist** [comment]
Hi @jcox10 ! I think this is the same issue as #52 , where the JSON in the `collection_info` property gets truncated. In #52 it's triggered by a direct publish.
In your case if you're using proxying, it probably got put into artifactory with the truncated info and now it will always read it directly from there and crash.

You should be able to confirm in artifactory that the collection in question has truncated/invalid JSON in the `collection_info` property.

If so, you could give #54 a try.

I'm a bit behind on PRs but I do still intend to put some version of that fix in.

If this is a truncated info issue, it would be super helpful if you're able to find out how/why the field gets truncated in your artifactory instance; I haven't been able to reproduce it in any of my environments.

There's a suggestion here that the limit may be dependent on which database backs artifactory, so that could be another data point that might help:
https://jfrog.atlassian.net/browse/RTFACT-27074

**Comment by jcox10** [comment]
This https://github.com/briantist/galactory/pull/59 should fix it!
